database:
  driver: mysql
  connection: root:1234@tcp(127.0.0.1:33306)/hublabs_login?charset=utf8&parseTime=True&loc=Local
behaviorLog:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: behaviorlog
debug: true
serviceName: login-api
httpPort:     8002
colleagueApi: http://localhost:80/colleague-api